# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-CA"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Jeffrey Wong"
title_separator          : "-"
name                     : &name "Jeffrey Wong"
description              : &description "Jeffrey Wong is a health services researcher and MSc student in the Faculty of Health Sciences at Simon Fraser University researching social prescribing, primary care, and digital health implementation."   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : "https://itsjeffreywong.github.io" # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "itsjeffreywong/itsjeffreywong.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Jeffrey Wong"
  bio              : "MSc Student, Faculty of Health Sciences, Simon Fraser University"
  location         : "Burnaby, Canada"
  email            : "jow3@sfu.ca" 

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=eZD4IMsAAAAJ"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : "https://orcid.org/0009-0005-8028-3585"
  semantic         : # URL
  ssrn             : # URL
  pubmed           : "https://www.ncbi.nlm.nih.gov/myncbi/jeffrey.wong.7/bibliography/public"
  researchgate     : "https://www.researchgate.net/profile/Jeffrey-Wong-33"
  scopus           : # URL
  zotero           : # URL


  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : # Username
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  artstation       : # Username
  bluesky          : "jeffrey.cspsc.ca"
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : "itsjeffreywong"
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
  reports:
    title: 'Reports'

# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/ for social media previews
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false      #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : true      # show this again if you add a blog
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Social media default site image
og_description           : *description
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : "Jeffrey Wong"
  links:
    - "https://scholar.google.com/citations?user=eZD4IMsAAAAJ"
    - "https://orcid.org/0009-0005-8028-3585"
    - "https://macisaacnursing.ubc.ca/our-people/jeffrey-wong"
    - "https://bsky.app/profile/jeffrey.cspsc.ca"
    - "https://linkedin.com/in/itsjeffreywong"
    

# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  # Hide the original template examples if they have not been deleted yet.
  - _data/authors.yml
  - _data/comments/layout-comments/comment-1470944006665.yml
  - _data/comments/layout-comments/comment-1470944162041.yml
  - _data/comments/markup-syntax-highlighting/comment-1470969665387.yml
  - _data/comments/welcome-to-jekyll/comment-1470942205700.yml
  - _data/comments/welcome-to-jekyll/comment-1470942247755.yml
  - _data/comments/welcome-to-jekyll/comment-1470942265819.yml
  - _data/comments/welcome-to-jekyll/comment-1470942493518.yml
  - _data/cv.json
  - _drafts/post-draft.md
  - _pages/archive-layout-with-content.md
  - _pages/category-archive.html
  - _pages/collection-archive.html
  - _pages/cv-json.md
  - _pages/markdown.md
  - _pages/non-menu-page.md
  - _pages/page-archive.html
  - _pages/portfolio.html
  - _pages/tag-archive.html
  - _pages/talkmap.html
  - _pages/terms.md
  - _pages/year-archive.html
  - _posts/2012-08-14-blog-post-1.md
  - _posts/2013-08-14-blog-post-2.md
  - _posts/2014-08-14-blog-post-3.md
  - _posts/2015-08-14-blog-post-4.md
  - _posts/2199-01-01-future-post.md
  - _publications/2009-10-01-paper-title-number-1.md
  - _publications/2010-10-01-paper-title-number-2.md
  - _publications/2015-10-01-paper-title-number-3.md
  - _publications/2024-02-17-paper-title-number-4.md
  - _publications/2025-06-08-paper-title-number-5.md
  - _talks/2012-03-01-talk-1.md
  - _talks/2013-03-01-tutorial-1.md
  - _talks/2014-02-01-talk-2.md
  - _talks/2014-03-01-talk-3.md
  - _teaching/2014-spring-teaching-1.md
  - _teaching/2015-spring-teaching-2.md
  - files/bibtex1.bib
  - files/paper1.pdf
  - files/paper2.pdf
  - files/paper3.pdf
  - files/slides1.pdf
  - files/slides2.pdf
  - files/slides3.pdf
  - talkmap/leaflet_dist/MarkerCluster.Default.css
  - talkmap/leaflet_dist/MarkerCluster.css
  - talkmap/leaflet_dist/leaflet.markercluster-src.js
  - talkmap/leaflet_dist/leaflet.markercluster.js
  - talkmap/leaflet_dist/screen.css
  - talkmap/map.html
  - talkmap/org-locations.js
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
